// Fill out your copyright notice in the Description page of Project Settings.


#include "Bullet.h"

// Sets default values
ABullet::ABullet()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	// ЙпЛчУМ collision АќИЎ
	CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("SphereComponent"));
	CollisionComponent->SetCollisionProfileName(TEXT("Projectile"));
	CollisionComponent->OnComponentHit.AddDynamic(this, &ABullet::OnHit); // componentПЁ hit eventАЁ ЙпЛ§ЧпРЛ ЖЇ, OnHit functionРЛ ШЃУтЧЯЕЕЗЯ binding
	CollisionComponent->InitSphereRadius(15.0f);
	RootComponent = CollisionComponent;

	// ЙпЛчУМ mesh
	ProjectileMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ProjectileMesh"));
	ProjectileMesh->SetupAttachment(RootComponent);
	static ConstructorHelpers::FObjectFinder<UStaticMesh> meshFinder(TEXT("/Game/ShootingGame/Asset/Sphere.Sphere"));
	if (meshFinder.Succeeded())
	{
		ProjectileMesh->SetStaticMesh(meshFinder.Object);
		ProjectileMesh->SetRelativeScale3D(FVector(0.02f, 0.02f, 0.02f));
		ProjectileMesh->SetCollisionProfileName(TEXT("Projectile"));
	}
	static ConstructorHelpers::FObjectFinder<UMaterial> materialFinder(TEXT("/Game/ShootingGame/Material/M_Metal_Steel.M_Metal_Steel"));
	if (materialFinder.Succeeded())
	{
		ProjectileMesh->SetMaterial(0, materialFinder.Object);
	}

	// ЙпЛчУМ movement
	ProjectileMovementComponent = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovementComponent"));
	ProjectileMovementComponent->SetUpdatedComponent(RootComponent);
	ProjectileMovementComponent->InitialSpeed = 3000.0f;
	ProjectileMovementComponent->MaxSpeed = 3000.0f;
	ProjectileMovementComponent->bRotationFollowsVelocity = true; // velocityРЧ ЙцЧтПЁ ЕћЖѓ ЙпЛчУМАЁ ШИРќЧЯАд ЕЪ
	ProjectileMovementComponent->bShouldBounce = true; // ЙпЛчУМПЁ bounceИІ РћПы
	ProjectileMovementComponent->Bounciness = 0.3f; // bounce ШФПЁ КИСИЕЧДТ velocity

	// ЙпЛчУМ СіМг НУАЃ
	InitialLifeSpan = 3.0f;
}

// Called when the game starts or when spawned
void ABullet::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void ABullet::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

// HitComponent : РЬ Actor ГЛПЁМ­ collisionРЬ ЙпЛ§Чб component (ПЉБтМБ spherecomponent)
// OtherActor : collisionРЬ ЙпЛ§Чб ЙнДыТЪ Actor
// OtherComponent : collisionРЬ ЙпЛ§Чб ЙнДыТЪ component
// NormalImpulse : impulse vector 
void ABullet::OnHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult& Hit)
{
	if (OtherActor != this && OtherComponent->IsSimulatingPhysics()) // other objectАЁ physicsИІ НЧЧрЧЯДТ АцПь, hitting resultИІ РћПыЧиОп Чд
	{
		OtherComponent->AddImpulseAtLocation(ProjectileMovementComponent->Velocity * 100.0f, Hit.ImpactPoint);
	}
}

// projectileРЧ velocityИІ АсСЄ
void ABullet::FireInDirection(const FVector& ShootDirection)
{
	ProjectileMovementComponent->Velocity = ShootDirection * ProjectileMovementComponent->InitialSpeed;
}
